name: Generate Subject Report

on:
  workflow_dispatch:
    inputs:
      subjectid:
        description: 'Subject ID to generate report for'
        required: true
      username:
        description: 'GitHub Username'
        required: true

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate User Authorization
      run: |
        users=$(jq -r '.allowed_users[]' src/authorized_users.json)
        if [[ ! " ${users[@]} " =~ " ${{ github.event.inputs.username }} " ]]; then
          echo "Unauthorized user"
          exit 1
        fi
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate Report
      env:
        LAMPACCESSKEY: ${{ secrets.LAMPACCESSKEY }}
        LAMPSERVERKEY: ${{ secrets.LAMPSERVERKEY }}
        REDCAPAPI: ${{ secrets.REDCAPAPI }}
      run: python src/generate_report.py ${{ github.event.inputs.subjectid }}
    
    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: subject-report
        path: reports/DNreport.html
